spring:
  datasource:
    url: jdbc:h2:mem:taskforcedb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
